app/models/book.py
import datetime

class Book:

    def __init__(self, title, author, pages, publish_date, description, isbn):
        self.title = title
        self.author = author
        self.pages = pages
        self.publish_date = publish_date
        self.description = description
        self.isbn = isbn
    

    def to_json(self):
        return {
            'title': self.title,
            'author': self.author,
            'pages': self.pages,
            'publish_date': datetime.datetime.strptime(str(self.publish_date), "%Y-%m-%d"),
            'description': self.description,
            'isbn': self.isbn
        }

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField, DateField
from wtforms.validators import DataRequired

class BookForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    pages = IntegerField('Pages', validators=[DataRequired()])
    publish_date = DateField('Publish Date', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    isbn = StringField('ISBN', validators=[DataRequired()])
    submit = SubmitField('Create book')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from app.routes.book import book_router
from app.config import Config


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    Bootstrap(app)
    
    app.register_blueprint(book_router)
    
    return app

app/routes/book.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.forms import BookForm
from app.db import db
from app.models.book import Book

book_router = Blueprint('book_router', __name__)


@book_router.route('/')
def index():
    books = db.books.find()
    return render_template('index.html', books=books)


@book_router.route('/store-book', methods=['GET', 'POST'])
def store_book():
    book_form = BookForm()

    if request.method == 'POST':
        if book_form.validate_on_submit():
            new_book = Book(
                book_form.title.data,
                book_form.author.data,
                book_form.pages.data,
                book_form.publish_date.data,
                book_form.description.data,
                book_form.isbn.data

            )
            
            db.books.insert_one(new_book.to_json())
            
            flash('Book created successfully', 'success')

            return redirect(url_for('book_router.index'))

    return render_template('store-book.html', book_form=book_form)

app/templates/base.html
{% extends "bootstrap/base.html" %} {% block body %}
<div class="container">
  {% for message in get_flashed_messages(category_filter=['success']) %}
  <div class="alert alert-success alert-dismissible">
    <button class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %} {% for message in get_flashed_messages(category_filter=['error'])
  %}
  <div class="alert alert-danger alert-dismissible">
    <button class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %} {% block content %} {% endblock %}
</div>

{% block scripts %} {{ super() }} {% endblock %} {% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}

<h1>Lista de libros</h1>
<a href="{{ url_for('book_router.store_book') }}">Crear un libro</a>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Author</th>
        <th>Title</th>
        <th>Pages</th>
        <th>Publish date</th>
        <th>Description</th>
        <th>ISBN</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for book in books %}
      <tr>
        <td>{{ book.author }}</td>
        <td>{{ book.title }}</td>
        <td>{{ book.pages }}</td>
        <td>{{ book.publish_date }}</td>
        <td>{{ book.description }}</td>
        <td>{{ book.isbn }}</td>
        <td>
          <button class="btn btn-warning">Edit</button>
          <button class="btn btn-danger">Delete</button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

app/templates/store-book.html
{% extends "base.html" %} {% block content %}

{% import 'bootstrap/wtf.html' as wtf %}

<h1>Crear libro</h1>

{{ wtf.quick_form(book_form) }}

{% endblock content %}